# Generated by GitHub Copilot
"""
Streamlit UI — Chat with PDF
Upload a PDF → index it → ask questions → get answers
"""

import os
import tempfile

import streamlit as st
from sentence_transformers import SentenceTransformer

from indexer import build_index, EMBED_MODEL_NAME, INDEX_FILE
from retriever import get_answer, load_llm


# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(page_title="Chat with PDF", page_icon="📄", layout="centered")
st.title("📄 Chat with PDF")
st.caption("Powered by FAISS + Sentence Transformers + Llama 3.2 via Ollama")


# ── Cache the embedding model so it loads only once ──────────────────────────
@st.cache_resource(show_spinner="Loading embedding model...")
def load_embed_model() -> SentenceTransformer:
    """Load and cache the sentence-transformer embedding model."""
    return SentenceTransformer(EMBED_MODEL_NAME)


@st.cache_resource(show_spinner="Loading LLM (first run downloads ~250MB)...")
def load_llm_model():
    """No-op — Ollama runs as a background service, no loading needed."""
    return load_llm()


embed_model = load_embed_model()
llm = load_llm_model()


# ── Sidebar — PDF upload & indexing ──────────────────────────────────────────
with st.sidebar:
    st.header("Upload PDF")
    uploaded_file = st.file_uploader("Choose a PDF file", type="pdf")

    if uploaded_file:
        if st.button("Index PDF", type="primary", use_container_width=True):
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
                tmp.write(uploaded_file.read())
                tmp_path = tmp.name

            with st.spinner("Running indexing pipeline..."):
                num_chunks = build_index(tmp_path)

            os.unlink(tmp_path)
            st.session_state["indexed"] = True
            st.session_state["messages"] = []
            st.success(f"Indexed {num_chunks} chunks!")

    if st.session_state.get("indexed"):
        st.info("PDF is ready. Ask your questions below.")


# ── Chat interface ────────────────────────────────────────────────────────────
if not st.session_state.get("indexed"):
    st.info("Upload and index a PDF from the sidebar to get started.")
else:
    # Display chat history
    for msg in st.session_state.get("messages", []):
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    # Handle new user input
    if query := st.chat_input("Ask a question about your PDF..."):
        st.session_state["messages"].append({"role": "user", "content": query})
        with st.chat_message("user"):
            st.write(query)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                answer = get_answer(query, embed_model, llm)
            st.write(answer)

        st.session_state["messages"].append({"role": "assistant", "content": answer})
