# Generated by GitHub Copilot
"""
Indexing Pipeline (runs once, offline, per document)
Flow: PDF file → Extract text → Chunk text → Embed chunks → Store in FAISS
"""

import fitz  # PyMuPDF
import faiss
import numpy as np
import pickle
from sentence_transformers import SentenceTransformer

EMBED_MODEL_NAME = "all-MiniLM-L6-v2"
INDEX_FILE = "faiss_index.bin"
CHUNKS_FILE = "faiss_chunks.pkl"

CHUNK_SIZE = 500   # words per chunk
CHUNK_OVERLAP = 50 # overlapping words between chunks


def extract_text(pdf_path: str) -> str:
    """Extract all text from a PDF file."""
    doc = fitz.open(pdf_path)
    return "".join(page.get_text() for page in doc)


def chunk_text(text: str) -> list[str]:
    """Split text into overlapping word-based chunks."""
    words = text.split()
    chunks = []
    for i in range(0, len(words), CHUNK_SIZE - CHUNK_OVERLAP):
        chunk = " ".join(words[i : i + CHUNK_SIZE])
        if chunk:
            chunks.append(chunk)
    return chunks


def embed_chunks(chunks: list[str], model: SentenceTransformer) -> np.ndarray:
    """Convert text chunks into vector embeddings."""
    embeddings = model.encode(chunks, show_progress_bar=True)
    return np.array(embeddings, dtype=np.float32)


def store_in_faiss(embeddings: np.ndarray, chunks: list[str]) -> None:
    """Store embeddings in a FAISS flat L2 index and save chunks to disk."""
    dimension = embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    index.add(embeddings)

    faiss.write_index(index, INDEX_FILE)
    with open(CHUNKS_FILE, "wb") as f:
        pickle.dump(chunks, f)


def build_index(pdf_path: str) -> int:
    """
    Full indexing pipeline entry point.
    Returns the number of chunks indexed.
    """
    model = SentenceTransformer(EMBED_MODEL_NAME)

    text = extract_text(pdf_path)
    chunks = chunk_text(text)
    embeddings = embed_chunks(chunks, model)
    store_in_faiss(embeddings, chunks)

    return len(chunks)
