# Generated by GitHub Copilot
"""
Query Pipeline (runs live, per user question)
Flow: User query → Embed query → Retrieve chunks → Build prompt → Answer
"""

import faiss
import numpy as np
import pickle
import ollama
from sentence_transformers import SentenceTransformer

from indexer import EMBED_MODEL_NAME, INDEX_FILE, CHUNKS_FILE

TOP_K = 5           # number of chunks to retrieve
LLM_MODEL = "llama3.2"  # Ollama model (run: ollama pull llama3.2)


def embed_query(query: str, model: SentenceTransformer) -> np.ndarray:
    """Embed the user query into a vector."""
    return np.array([model.encode(query)], dtype=np.float32)


def retrieve_chunks(query_embedding: np.ndarray) -> list[str]:
    """Search FAISS index and return the top-k most relevant chunks."""
    index = faiss.read_index(INDEX_FILE)
    with open(CHUNKS_FILE, "rb") as f:
        chunks = pickle.load(f)

    _, indices = index.search(query_embedding, TOP_K)
    return [chunks[i] for i in indices[0] if i < len(chunks)]


def build_prompt(query: str, chunks: list[str]) -> str:
    """Assemble a prompt from retrieved context and the user query."""
    context = "\n\n".join(chunks)
    return (
        "Use only the context below to answer the question. "
        "If the answer is not in the context, say 'I don't know'.\n\n"
        f"Context:\n{context}\n\n"
        f"Question: {query}\n\nAnswer:"
    )


def load_llm() -> None:
    """No-op — Ollama manages the model process externally."""
    return None


def get_answer(query: str, embed_model: SentenceTransformer, llm=None) -> str:
    """
    Full query pipeline entry point.
    Returns the LLM's answer as a string.
    """
    query_embedding = embed_query(query, embed_model)
    chunks = retrieve_chunks(query_embedding)
    prompt = build_prompt(query, chunks)

    response = ollama.chat(
        model=LLM_MODEL,
        messages=[{"role": "user", "content": prompt}],
    )
    return response["message"]["content"]
